engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - less
      - jade
  csslint:
    enabled: true
  fixme:
    enabled: true
    config:
      languages:
      - javascript
      - less
      - jade
  nodesecurity:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
  - app-build/**
  - routes/**
  - bin/**
  - views/**
  - "**/*.js"
  - "**/*.less"
  - "**/*.jade"
exclude_paths:
  - bower_components/**/*
  - node_modules/**/*
  - public/**/*
