engines:
  duplication:
    enabled: true
  csslint:
    enabled: true
  fixme:
  	enabled: true
  nodesecurity:
  	enabled: true
  scss-lint:
  	enabled: true
  ratings:
    paths:
    - app-build/**
    - routes/**
    - bin/**
    - views/**
    - "**/*.js"
    - "**/*.less"
    - "**/*.jade"
  languages:
    - JavaScript: true
    - Less: true
    - Jade: true
  exclude_paths:
  - bower_components
  - bower_components/**
  - node_modules
  - node_modules/**
  - public
  - public/**